AWSTemplateFormatVersion: 2010-09-09
Description: >-
  
#################### Parameters #####################
#####################################################

Parameters:

    CloudFormationBucketName:
    Description: >-
      Bucket name for CloudFormation templates.
    Type: 'AWS::SSM::Parameter::Value<String>'

  RootAPILambda:
    Description: >-
      Bucket name for Lambda function
    Type: 'AWS::SSM::Parameter::Value<String>'
    
  LambdaS3Key:
    Description: >-
      Lambda file.
    Type: 'AWS::SSM::Parameter::Value<String>'
    
  SNSSubscriptions:
    Description: >-
      SNS Subscription Email.
    Type: 'AWS::SSM::Parameter::Value<String>'
    
  SNSTopicName:
    Description: >-
      SNSTopicName.
    Type: 'AWS::SSM::Parameter::Value<String>'
  
 
    

##################### Resources #####################
#####################################################     
    
Resources:

  Parameters:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref CloudFormationBucketName
          - 'RootAPIMonitor.yaml'
      Parameters:
        CloudFormationBucketName: !Ref CloudFormationBucketName
        RootAPILambda: !Ref RootAPILambda
        LambdaS3Key: !Ref LambdaS3Key
        SNSSubscriptions: !Ref SNSSubscriptions
        SNSTopicName: !Ref SNSSubscriptions
        

  RootAPILogin:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref CloudFormationBucketName
          - '/RootAPIMonitor.yaml'
    DependsOn:
      - Parameters
